title: TENSS 2019
description: A course on Bonsai visual programming developed by NeuroGEARS, Ltd.
funding: This advanced training course was prepared for the Transylvanian Experimental Neuroscience Summer School 2019.
funding_logo: tenss
funding_url: https://www.tenss.ro/
google_analytics:
theme: minima
baseurl: "/tenss-2019"

twitter_username: bonsai_rx
github_username:  neurogears

plugins:
  - jekyll-seo-tag

include:
  - _pages
  - _slides

exclude:
  - Gemfile
  - Gemfile.lock
  - "**README.md"

header_pages:
  - _pages/slides.md
  - _pages/worksheets.md

collections:
  # Ideally we would use collections for slides but this
  # breaks reveal.js markdown processing because of issue:
  # https://github.com/jekyll/jekyll/issues/6209
  # slides:
  #   output: true
  #   permalink: /:collection/:path/
  
  worksheets:
    output: true
    permalink: /:collection/:path/
